### ISSUE TITLE
Unzip failure error during import does not indicate the file name

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#670]
...as there can be a few of them during an operation.

```
2021-05-07 06:20:55,481:API_operations.helpers.JobService:ERROR Unexpected termination of #43172
2021-05-07 06:20:55,481:API_operations.helpers.JobService:ERROR File is not a zip file
Traceback (most recent call last):
  File "/app/API_operations/helpers/JobService.py", line 72, in run_in_background
    self.do_background()
  File "/app/API_operations/imports/Import.py", line 74, in do_background
    self.do_validate()
  File "/app/API_operations/imports/Import.py", line 112, in do_validate
    how, diag, nb_rows = self._collect_existing_and_validate(source_dir_or_zip, loaded_files)
  File "/app/API_operations/imports/Import.py", line 139, in _collect_existing_and_validate
    source_bundle = InBundle(source_dir_or_zip, bundle_temp_dir)
  File "/app/BO/Bundle.py", line 45, in __init__
    for a_bundle in self.path.glob(self.UVP6_FILTER)]
  File "/app/BO/Bundle.py", line 45, in <listcomp>
    for a_bundle in self.path.glob(self.UVP6_FILTER)]
  File "/app/BO/Bundle.py", line 298, in __init__
    with zipfile.ZipFile(path.as_posix(), 'r') as z:
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

```

**Comment by grololo06** [comment]
In user hints, we need to add as well possible causes (interrupted or still in-progress file transfer)
